machine_learning:
  model_version: 'latest'  # config parameter not used yet

  prboability_thresholds:
    general: 0.7
    multi_phase: 0.95

  guardrail_metrics:
    max_number_of_false_positives: 0  # config parameter not used yet
    min_recall: 0.95  # config parameter not used yet
    min_precision: 0.9  # config parameter not used yet
    min_f1_score: 0  # config parameter not used yet
  
  exclude_features:  # config parameter not used yet
    # - bla
    # - bla
    # - bla

  include_features:  # config parameter not used yet
    # - bla
    # - bla
    # - bla

flask_app:
  debug: False
  test: False

daily_routine:
  test: False
  exit_if_stale: False
  scrape_source:
    - dcn
    - ocn
  steps:
    - scrape
    - train
    - validate
    - match
