machine_learning:
  model_version: 'latest'  # config parameter not used yet

  prboability_thresholds:
    general: 0.2
    multi_phase: 0.5

  guardrail_metrics:
    min_recall: 1  # config parameter not used yet
    min_precision: 0.9  # config parameter not used yet

  exclude_features:
    -
    # - city_score
    # - city_pr_score
    # - total_score


flask_app:
  debug: False
  adhoc_ssl: False
  test: False
  show_summary:
    cert_limit: 1600  # config parameter not used yet
  max_free_requests : 4
  free_timeout_length : 2
  free_session_length : 5

daily_routine:
  test: False
  scrape_source:
    - dcn
    - ocn
    - l2b
  steps:
    - train
    - validate
    - match
